In [1]:
import pandas as pd 
import numpy as np 
from scipy import stats
from scipy.stats import norm

In [2]:
data=pd.read_csv(r'BuyerRatio (1).csv')

In [3]:
data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [6]:
data_table=data.iloc[:,1:6]
data_table

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [8]:
data_table.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [9]:
val=stats.chi2_contingency(data_table)

In [10]:
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [11]:
type(val)

tuple

In [12]:
no_of_rows=len(data_table.iloc[0:2,0])
no_of_columns=len(data_table.iloc[0,0:4])
degree_of_f=(no_of_rows-1)*(no_of_columns-1)
print('Degree of Freedom=',degree_of_f)

Degree of Freedom= 3


In [13]:
Expected_value=val[3]

In [14]:
Expected_value

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [16]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(data_table.values,Expected_value)]) #Pearson’s chi-squared test-statistic 
chi_square_statestic=chi_square[0]+chi_square[1]
chi_square_statestic

1.5152956451130446

In [17]:
critical_value=chi2.ppf(0.95,3) #Percentage point function
critical_value

7.814727903251179

In [20]:
if chi_square_statestic >= critical_value:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')

Independent (fail to reject H0)


In [21]:
pvalue=1-chi2.cdf(chi_square_statestic,3)
pvalue

0.6787446296467897